### ISSUE TITLE
Support Server Side calls

### ISSUE THREAD

**Issue by Domitnator** [Domitnator/kenticocloud-nuxt-module#5]
Server side calls are throwing an exception.

For example:

```js
asyncData ({ app }) {
      app.$deliveryClient.items().type('page').get().toPromise().then((response) => { 
        return { list: response.items } 
      });
  },
```
is throwin an exception:

"XMLHttpRequest is not supported by your browser"

![image](https://user-images.githubusercontent.com/13468638/38471560-26ea8b7a-3b73-11e8-9438-c8f90bcb8ddb.png)

**Comment by Enngage** [comment]
Hey, I released new version which includes node.js support ootb. We also renamed package on npm to [kentico-cloud-delivery](https://www.npmjs.com/package/kentico-cloud-delivery)

**Comment by Domitnator** [comment]
kenticocloud-nuxt-module now uses the new Kentico Cloud Delivery SDK. So server side calls are now supported!

**Comment by Enngage** [comment]
Awesome, looks good! One thing I noticed in your readme is that you say that only Promises are supported (I'm not familiar with Nuxt at all) and in that case you might actually be ok with leaving the rxjs out of the dependencies because you won't be using its operators anyway. I have [this example](https://github.com/Enngage/kentico-cloud-js/blob/master/packages/delivery/demo/umd-promise/index.html) without rxjs completely

**Comment by Domitnator** [comment]
I already tried removing the dependency but the Nuxt project won't compile without the rxjs dependency:

![image](https://user-images.githubusercontent.com/13468638/40544631-465425cc-6029-11e8-9ebb-1443b34b2503.png)

**Comment by Enngage** [comment]
ah, I see. In that case its ok :) It likely works only with UMD modules and
not the ones that you need to build, which is probably what most people
would be doing anyway.
